title = "Matt DiBiaso a.k.a Wise Monkey"                
baseURL = "https://wisemonkey.xyz"        
relativeURLs = true
theme = "smore"
enableEmoji = true

     
# Sets the amount of blog posts that appear before creating a new page
paginate = 15

# Set the parameters for your site
[params]
author = "Matt DiBiaso"
description = "Site Description"
# path to a .ico to use as favicon
favicon = "favicon.ico"  

# Define syntax highlighting
[markup]
  [markup.highlight]
   anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true 
    lineNumbersInTable = false 
    noClasses = true
    noHl = false
    style = 'gruvbox'
    tabWidth = 4
